apiVersion: skaffold/v2beta10
kind: Config
metadata:
    name: stack

build:
  artifacts:
  - image: stack_backend
    context: apps/backend

deploy:
  helm:
    releases:
      - name: pg-operator
        namespace: apps
        createNamespace: true
        wait: true
        chartPath: charts/postgres-operator
      - name: stack
        namespace: default
        createNamespace: false
        chartPath: charts/stack
        artifactOverrides:
          backend:
            image: stack_backend
        imageStrategy:
          helm: {}

portForward:
- resourceType: deployment
  resourceName: stack-backend
  namespace: default
  port: 1337
  localPort: 1337