FROM strapi/base:14-alpine

ARG STRAPI_VERSION
RUN yarn global add @strapi/strapi@${STRAPI_VERSION-4.1.5}

RUN mkdir /srv/app && chown 1000:1000 -R /srv/app

WORKDIR /srv/app

VOLUME /srv/app

COPY --chown=1000:1000 docker-entrypoint.sh /usr/local/bin
RUN chmod 755 /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT [ "/usr/local/bin/docker-entrypoint.sh" ]
#CMD ["npm", "start"]
CMD ["strapi", "develop"]