apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stack.backend.fullname" . }}
  labels:
    {{- include "stack.backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "stack.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stack.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "stack.backend.image" . }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: backend
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            httpGet:
              path: /
              port: backend
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            httpGet:
              path: /
              port: backend
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          env:
            - name: DATABASE_HOST
              value: {{ (lookup "v1" "Service" "default" (include "stack.database.fullname" .)).spec.clusterIP | quote }}
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "db"
            - name: DATABASE_USERNAME
              value: {{ (lookup "v1" "Secret" "default" (printf "backend-user.%s.credentials.postgresql.acid.zalan.do" (include "stack.database.fullname" .) ) ).data.username | b64dec | quote }}
            - name: DATABASE_PASSWORD
              value: {{ (lookup "v1" "Secret" "default" (printf "backend-user.%s.credentials.postgresql.acid.zalan.do" (include "stack.database.fullname" .) ) ).data.password | b64dec | quote }}
            - name: DATABASE_SSL
              value: "true"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
