version: "3"

services:
  app:
    image: stack_backend:b65e0ae8eeaa6c60a72bb45a0159d542444e29159aba03815c65cd1ae2d38229
    container_name: strapi_v4_app
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: app
      DATABASE_USERNAME: db_username
      DATABASE_PASSWORD: db_password
    volumes:
      - ./backend:/srv/app
      - ./.tmp/node_modules:/srv/app/node_modules
    ports:
      - 1338:1337
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: strapi_v4_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: db_username
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./.tmp/data:/var/lib/postgresql/data