version: '3'

services:

  frontend:
    restart: unless-stopped    
    build: 
      context: ./frontend
      dockerfile: Dockerfile.arm64v8
    environment:
      API_URL: strapi:1337
    volumes:
      - ./frontend:/home/appuser/srv/app
    ports:
      - '3000:3000'

  strapi:
    command: npm run dev
    restart: unless-stopped
    build: 
      context: ./backend
      dockerfile: Dockerfile.arm64v8
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./backend:/home/appuser/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./.tmp/data:/var/lib/postgresql/data
