apiVersion: v1
kind: Service
metadata:
  name: {{ include "stack.fullname" . }}
  labels:
    {{- include "stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: frontend
      protocol: TCP
      name: frontend
  selector:
    {{- include "stack.selectorLabels" . | nindent 4 }}
